# Generated by Django 4.2.6 on 2023-11-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employees_imaage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Imaage',
            new_name='Profile_pic',
        ),
    ]
