# Generated by Django 4.2.6 on 2023-11-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_profile_pic_employees_profile_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Profile_pics',
            new_name='Profile_pic',
        ),
    ]
